meta:
  stemcell: (( param "please set stemcell" ))

name: (( grab meta.environment ))

director_uuid: (( param "please set director_uuid" ))

releases: (( param "please set release" ))

jobs: (( param "please set jobs" ))

compilation:
  workers: 6
  network: broker_registrar1
  reuse_compilation_vms: true
  cloud_properties: (( param "please set compilation cloud properties" ))

update:
  canaries: 1
  max_in_flight: 50
  canary_watch_time: 1000-60000
  update_watch_time: 1000-60000
  serial: false

resource_pools:
  - name: small_z1
    network: broker_registrar1
    stemcell: (( grab meta.stemcell ))
    cloud_properties: (( param "please set resource_pool cloud properties" ))

networks: (( param "please set networks" ))
